package com.example.myapplication2.HomeWorkThree

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel

class FilmsViewModel : ViewModel() {

    var inputCount by mutableStateOf("")
        private set
    var isGenerated by mutableStateOf(false)
        private set

    val isValidNumber: Boolean
        get() = inputCount.toIntOrNull()?.let { it > 0 } ?: false

    var filterQuery by mutableStateOf("")
        private set
    var filteredFilms by mutableStateOf<List<FilmModel>>(emptyList())
        private set

    fun onInputCountChange(newValue: String) {
        inputCount = newValue
    }

    fun onFilterQueryChange(newValue: String) {
        filterQuery = newValue
    }

    fun generateFilms() {
        val count = inputCount.toIntOrNull() ?: 0
        DataRepository.generateRandomFilms(count)
        isGenerated = true
        filteredFilms = DataRepository.getFilms()
    }

    fun applyFilter() {
        val yearLimit = filterQuery.toIntOrNull()
        filteredFilms = if (yearLimit == null) {
            DataRepository.getFilms()
        } else {
            DataRepository.getFilms().filter { it.releaseDate <= yearLimit }
        }
    }
}